import { MIGRATION_ATTRIBUTES, REQUEST_ERRORS, RESULT_STATUSES } from './userMigration.js';

// /migrate/spec.md: the user migration protocol, written for a coding agent that adds it to an
// application. It is the same for every application; what differs per application (return URLs,
// signing method) the agent reads from /migrate/check with a request it signed, and the client ID
// and secret come from the application's own configuration. Keep it in step with routes/migrate.js.

const json = (value) => ['```json', JSON.stringify(value, null, 2), '```'];

export function migrationSpec({ siteUrl }) {
  const migrateUrl = `${siteUrl}/migrate`;
  const statuses = Object.keys(RESULT_STATUSES);

  const requestSchema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'CloakTail user migration request (JWT claims)',
    type: 'object',
    required: ['iss', 'aud', 'iat', 'exp', 'jti', 'sub', 'preferred_username', 'return_url'],
    properties: {
      iss: { type: 'string', description: 'The application’s client ID in CloakTail: its OIDC client ID or SAML entity ID.' },
      aud: { const: migrateUrl, description: 'Or an array containing it.' },
      iat: { type: 'integer', description: 'Now, in seconds since 1970.' },
      exp: { type: 'integer', description: 'At most iat + 600.' },
      jti: { type: 'string', minLength: 1, maxLength: 200, description: 'A new random id (e.g. a UUID) for every request. Each is accepted once.' },
      sub: { type: 'string', minLength: 1, maxLength: 255, description: `The user’s id in the application. Stored in Keycloak as the ${MIGRATION_ATTRIBUTES.legacyId} attribute.` },
      preferred_username: { type: 'string', pattern: '^[^\\s\\x00-\\x1f\\x7f]{1,255}$', description: 'The Keycloak username. Keycloak stores it lowercase.' },
      email: { type: 'string', format: 'email', maxLength: 254 },
      given_name: { type: 'string', maxLength: 100 },
      family_name: { type: 'string', maxLength: 100 },
      return_url: { type: 'string', format: 'uri', description: 'Exactly one of the application’s registered return URLs.' },
      state: { type: 'string', maxLength: 500, description: 'A random value kept in the user’s pre-login session. Returned unchanged in the result.' },
    },
  };

  const resultSchema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'CloakTail user migration result (JWT claims, HS256)',
    type: 'object',
    required: ['iss', 'aud', 'sub', 'iat', 'exp', 'jti', 'request_jti', 'status', 'preferred_username'],
    properties: {
      iss: { const: migrateUrl },
      aud: { type: 'string', description: 'The application’s client ID.' },
      sub: { type: 'string', description: 'The sub of the request: the user’s id in the application.' },
      iat: { type: 'integer' },
      exp: { type: 'integer', description: 'iat + 300.' },
      jti: { type: 'string', description: 'Unique per result.' },
      request_jti: { type: 'string', description: 'The jti of the request this answers.' },
      status: { enum: statuses },
      preferred_username: { type: 'string', description: 'Lowercased.' },
      keycloak_id: { type: 'string', description: 'The Keycloak user id. With created and already_migrated.' },
      state: { type: 'string', description: 'The state of the request, when it had one.' },
      error_description: { type: 'string', description: 'For a person, with conflict, expired and error.' },
      simulated: { const: true, description: 'Only on results from POST /migrate/simulate.' },
    },
  };

  return [
    '# CloakTail user migration protocol',
    '',
    `> How an application moves its existing users into Keycloak through CloakTail at ${siteUrl}, one user at a time, as they sign in. Written for the developer and for a coding agent that implements it. Key words MUST, MUST NOT, SHOULD and MAY are as in RFC 2119.`,
    '',
    '## Overview',
    '',
    '1. The user signs in to the application with their old password, as today.',
    '2. If they aren’t migrated yet, the application doesn’t start a session. It redirects the browser to CloakTail with a **request**: a JWT it signs, saying who the user is.',
    '3. CloakTail shows the user their profile and asks for a new password (and, when the application requires OTP, has them add an authenticator app), then creates them in Keycloak (the sandbox realm).',
    '4. CloakTail redirects back to the application’s return URL with a **result**: a JWT signed with HS256 and the migration secret, carrying a `status`.',
    '5. The application checks the result, records the user as migrated and lets them in at once: they already signed in with their old password. From their next sign-in, they sign in with Keycloak (OIDC or SAML).',
    '',
    '## What you need',
    '',
    '| Value | Where it comes from |',
    '|---|---|',
    '| Client ID (`iss` of requests, `aud` of results) | The application’s existing Keycloak OIDC client ID or SAML entity ID, already in its configuration. Must be an application registered in CloakTail with user migration set up. |',
    '| Migration secret | Shown on the application’s CloakTail page, Applications → (app) → User migration. Read it from an environment variable, e.g. `CLOAKTAIL_MIGRATION_SECRET`. If it isn’t set, ask the developer to set it. Never ask for it in chat, print it, log it or commit it. |',
    '| Request signing key | The migration secret (HS256) by default. If the application chose a public key or JWKS URL on its migration page, its own private key. |',
    '| Return URLs, signing method, OTP setting | Registered on the migration page. Read them from `POST /migrate/check` (below) with a request you signed. |',
    `| CloakTail URLs | Start: \`${migrateUrl}/start\`. Request \`aud\` and result \`iss\`: \`${migrateUrl}\`. |`,
    '',
    '## Rules',
    '',
    '### Starting a migration',
    '',
    '- The application MUST check the user’s old password (and any second factor it has) before sending them to CloakTail. A request asserts who the user is; CloakTail trusts it.',
    '- It MUST keep a per-user flag, e.g. `migrated_at` and `keycloak_id`, and send only users without it. Migrated users sign in with Keycloak only.',
    '- It MUST NOT start a logged-in session before the result arrives. It SHOULD keep a short pre-login session holding `state` and the user’s id, lasting at least 30 minutes (the time CloakTail gives the user): after `created`, `cancelled`, `expired` or `error` it becomes the user’s session.',
    '- It MUST build and sign requests on the server. Secrets and private keys MUST NOT reach the browser.',
    '- Every request MUST have a new random `jti`, `iat` = now and `exp` at most 600 seconds later (300 is enough).',
    '- `return_url` MUST be byte-for-byte one of the registered return URLs (scheme, host, port, path, trailing slash, query).',
    '- `state` SHOULD be at least 128 random bits, stored in the pre-login session together with the user’s id (`sub`).',
    `- The application SHOULD send the request as an auto-submitted HTML form \`POST\` to \`${migrateUrl}/start\` with one field, \`request\`, which keeps the token out of logs and history. \`GET ${migrateUrl}/start?request=<JWT>\` also works.`,
    '- With HS256, the JWT header MUST be `{"alg":"HS256","typ":"JWT"}`. With a key pair, use RS256, PS256, ES256 or EdDSA; with a JWKS URL, set `kid`.',
    '',
    '### Handling the result',
    '',
    'The return URL receives `GET <return_url>?result=<JWT>`. The application MUST, before acting on it:',
    '',
    '1. Accept only `alg` `HS256` and verify the signature with the migration secret (constant-time comparison).',
    `2. Check \`iss\` is \`${migrateUrl}\` and \`aud\` is its client ID.`,
    '3. Check `exp` hasn’t passed (allow at most 60 seconds of clock skew).',
    '4. Check `state` equals the one in the pre-login session, then delete it from the session so it can’t be used twice. With no matching pre-login session, reject the result.',
    '5. Check `sub` equals the user id stored with that `state`.',
    '',
    'A result failing any check MUST be rejected: no session, no change to the user. Show a generic error and log the reason, without the token.',
    '',
    'Then act on `status`. An unknown status MUST be treated like `error`.',
    '',
    '| `status` | Meaning | The application |',
    '|---|---|---|',
    ...statuses.map((s) => `| \`${s}\` | ${RESULT_STATUSES[s].meaning} | ${RESULT_STATUSES[s].action} |`),
    '',
    '- Marking a user migrated means storing `migrated_at` and `keycloak_id`. It MUST be idempotent: `already_migrated` can arrive for a user marked before.',
    '- Results with `simulated: true` come only from `POST /migrate/simulate`. In production the application SHOULD treat them like `error`.',
    '- CloakTail keeps its own record of which Keycloak user each `sub` became. A request for a recorded `sub` whose Keycloak user still exists answers `already_migrated` at once, without asking for a password, even if the username changed.',
    '- `conflict` is resolved by a person: when the existing Keycloak account is the user’s, the developer links it to the `sub` (API `PUT /api/v1/apps/{id}/migration/users/{sub}`), and the next request answers `already_migrated`.',
    '',
    '### Recovering a lost result',
    '',
    'If a user was sent to CloakTail but never came back (tab closed, network drop), the account may exist while the application never recorded it. The application SHOULD then ask CloakTail from its server, with a new signed request for that user, through `POST /migrate/status` (below), and mark the user migrated when it answers `migrated: true`. It MAY do this at the user’s next sign-in, before sending them to CloakTail again. Sending them again is also safe: the answer is `already_migrated`.',
    '',
    '### Signing the user in',
    '',
    '- After `created`, the application SHOULD start the user’s session at once, from the pre-login session: they signed in with their old password (and any second factor) moments ago and just set up their Keycloak sign-in, so a second sign-in only slows them down. It MAY start a Keycloak sign-in instead when it needs Keycloak tokens straight away.',
    '- After `already_migrated`, and for every later sign-in of a migrated user, the application MUST start its normal Keycloak sign-in instead of checking the old password. Once a user is migrated, the old password alone MUST NOT let them in: their Keycloak password may have changed since.',
    '- With OIDC, it SHOULD pass `login_hint=<preferred_username>`. With SAML, it SHOULD put the username in the AuthnRequest’s `<saml:Subject><saml:NameID>`. (If the realm uses the email as username, users sign in with their email; pass the email instead.)',
    '- If the application requires OTP, the user adds an authenticator app on the CloakTail page and Keycloak asks for a code from it at each Keycloak sign-in. The application does nothing for it.',
    '',
    '## Schemas',
    '',
    '### Request',
    '',
    ...json(requestSchema),
    '',
    '### Result',
    '',
    ...json(resultSchema),
    '',
    '## Request errors',
    '',
    `When CloakTail turns a request down, the user only sees “This link can’t be used” and is not redirected. The application’s request history on its migration page shows the code and reason. \`POST /migrate/check\` returns the same codes, except that \`unknown_client\` and \`bad_signature\` are both reported as \`invalid_request\`.`,
    '',
    '| Code | Fix |',
    '|---|---|',
    ...Object.entries(REQUEST_ERRORS).map(([code, fix]) => `| \`${code}\` | ${fix} |`),
    '',
    '## Testing endpoints',
    '',
    'All three take the request JWT the application built, as JSON `{"request": "<JWT>"}` or a form field `request`, and answer JSON. They work only for requests signed by an application registered in CloakTail with user migration set up, also while migration is turned off. They create no users and don’t use up the `jti`. Limit: 120 calls per 15 minutes per IP address.',
    '',
    '### POST /migrate/check',
    '',
    'Validates a request exactly as `/migrate/start` would, and reports whether its `jti` was already used.',
    '',
    '```sh',
    `curl -s ${migrateUrl}/check -H 'Content-Type: application/json' -d '{"request":"<JWT>"}'`,
    '```',
    '',
    'Valid (HTTP 200):',
    '',
    ...json({
      ok: true,
      app: {
        client_id: 'my-app', name: 'My app', enabled: true, return_urls: ['https://myapp.example.com/migrated'],
        request_signing: 'HS256 with the migration secret', result_signing: 'HS256 with the migration secret', require_otp: true,
      },
      request: {
        sub: '42', preferred_username: 'alice', email: 'alice@example.com', given_name: 'Alice', family_name: null,
        return_url: 'https://myapp.example.com/migrated', state: '…', jti: '…',
      },
      start_url: `${migrateUrl}/start`,
    }),
    '',
    'With migration turned off, a valid request also gets `"warning": {"code": "migration_disabled", …}`: `/migrate/start` would refuse it until the developer turns migration on.',
    '',
    'Invalid (HTTP 400). `app` is included once the signature has checked out:',
    '',
    ...json({ ok: false, error: { code: 'return_url_unregistered', message: 'return_url "https://myapp.example.com/done" is not one of the registered return URLs.' }, app: { '…': '…' } }),
    '',
    '### POST /migrate/simulate',
    '',
    `Returns the result CloakTail would send for a valid request, with the \`status\` you choose (one of ${statuses.map((s) => `\`${s}\``).join(', ')}), signed with the migration secret and marked \`simulated: true\`. Use it to test every branch of the return URL handler.`,
    '',
    '```sh',
    `curl -s ${migrateUrl}/simulate -H 'Content-Type: application/json' -d '{"request":"<JWT>","status":"created"}'`,
    '```',
    '',
    ...json({ ok: true, status: 'created', result: '<JWT>', redirect_url: 'https://myapp.example.com/migrated?result=<JWT>' }),
    '',
    'Open `redirect_url` in the browser session that holds the matching `state`, or call the handler with it in a test.',
    '',
    '### POST /migrate/status',
    '',
    'Whether CloakTail migrated the request’s user (`sub`) for this application. Called by the application’s server to recover a lost result. A migrated user comes with a signed `already_migrated` result: check its signature, `iss`, `aud`, `exp` and `sub` as for any result, but not `state` (there is no browser session).',
    '',
    '```sh',
    `curl -s ${migrateUrl}/status -H 'Content-Type: application/json' -d '{"request":"<JWT>"}'`,
    '```',
    '',
    ...json({ ok: true, migrated: true, sub: '42', keycloak_id: '…', preferred_username: 'alice', migrated_at: '2026-10-03T07:51:14Z', result: '<JWT>' }),
    '',
    'Not migrated: `{"ok": true, "migrated": false, "sub": "42"}`.',
    '',
    '## Implementing it in an application',
    '',
    '### Find in the codebase',
    '',
    '- Where the old password is checked and the session is started (the login handler).',
    '- The user model and its storage: add `migrated_at` and `keycloak_id` with a schema migration.',
    '- The existing Keycloak OIDC or SAML sign-in: its client ID or entity ID is `iss`; its login start is where migrated users go.',
    '- How configuration and secrets are loaded: add `CLOAKTAIL_MIGRATION_SECRET` (and the private key, if requests use one).',
    '- A JWT library already in use, if any. HS256 can also be done with the standard library’s HMAC-SHA256.',
    '',
    '### Steps',
    '',
    '1. Add the user fields and configuration.',
    '2. In the login handler, after a correct old password: migrated user → Keycloak sign-in; otherwise create the pre-login session (`state`, user id) and send the request.',
    '3. Add the return URL route that checks the result and handles every status: after `created`, start the session from the pre-login session (no Keycloak sign-in); after `already_migrated`, start the Keycloak sign-in.',
    '4. Verify the request with `POST /migrate/check` until it returns `ok: true`; use `app.return_urls` for `return_url`.',
    '5. Test the return route with `POST /migrate/simulate` for every status.',
    '',
    '### Acceptance tests',
    '',
    '- A request built by the application passes `POST /migrate/check`.',
    '- Two requests never share a `jti`.',
    '- A migrated user is sent to Keycloak and never to CloakTail; a wrong old password never reaches CloakTail.',
    '- After `created`, the user is signed in to the application without another sign-in; after `already_migrated`, they are sent to Keycloak.',
    `- For each of ${statuses.map((s) => `\`${s}\``).join(', ')}, a simulated result leads to the behaviour in the status table.`,
    '- A result with a wrong signature, another `aud`, an expired `exp`, a different or reused `state`, or a `sub` that doesn’t match is rejected, with no session and the user unchanged.',
    '- A user whose result was lost is recognised: `POST /migrate/status` for them answers `migrated: true` and the application records them.',
    '- The migration secret appears in no log, response, browser page or committed file.',
    '',
    '## See also',
    '',
    `- [CloakTail for AI agents](${siteUrl}/llms.txt): the product, the sandbox realm’s IdP URLs, and Keycloak troubleshooting.`,
    '',
  ].join('\n');
}
