import { SCOPES, TOKEN_TTL_S, MAX_CREDENTIALS } from '../lib/apiCredentials.js';
import { config } from '../config.js';
import { endpointGroups } from './openapi.js';

// /api/v1/agent.md: how a coding agent uses the developer REST API (routes/api.js) to set up SSO and
// user migration for the developer's application, end to end. The OpenAPI document has the exact
// schemas; this has the facts, numbered rules, helpers, the order of calls, the choices to make and
// the "done when" criteria an agent checks before it stops. Its endpoint table is generated from the
// OpenAPI document. Keep the rest in step with routes/api.js.
//
// It names no host: every URL starts with $CLOAKTAIL_URL, the base URL the agent derives from where
// it fetched the guide (or finds in its environment). So one guide is right on every domain, and
// its shell commands run as written. They need only curl and node (or python3): no jq, which many
// machines (Windows in particular) don't have.

const table = (rows) => rows.map((r) => `| ${r.join(' | ')} |`);
const BASE = '$CLOAKTAIL_URL';
const api = `${BASE}/api/v1`;
const done = (items) => ['**Done when** (check each before you stop):', '', ...items.map((t) => `- [ ] ${t}`)];
const sh = (...lines) => ['```sh', ...lines, '```'];

// The shell helpers every recipe uses. Plain POSIX sh functions; node does the JSON and file work.
const HELPERS = [
  '# Reads one field of the JSON on stdin. Uses node, else python3.',
  'json_get() {',
  '  if command -v node >/dev/null 2>&1; then',
  '    node -e \'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const v=JSON.parse(s)[process.argv[1]];process.stdout.write(v==null?"":String(v))})\' "$1"',
  '  else',
  '    python3 -c \'import sys,json;v=json.load(sys.stdin).get(sys.argv[1]);sys.stdout.write("" if v is None else str(v))\' "$1"',
  '  fi',
  '}',
  '',
  '# Prints a new access token. The credential goes to curl on stdin (printf is a shell builtin),',
  '# so it never appears in a process list or shell history.',
  'ct_token() {',
  '  printf \'user = "%s:%s"\\n\' "$CLOAKTAIL_CLIENT_ID" "$CLOAKTAIL_CLIENT_SECRET" |',
  '    curl -s -K - -d grant_type=client_credentials "$CLOAKTAIL_URL/api/v1/oauth/token" | json_get access_token',
  '}',
  '',
  '# Copies the NAME=value lines of file $1 into file $2, replacing any line with the same NAME, then',
  '# deletes $1. Prints only the names it set. Running it twice changes nothing.',
  'env_merge() {',
  '  node -e \'const fs=require("fs"),[src,dest]=process.argv.slice(1);',
  '    const out=fs.existsSync(dest)?fs.readFileSync(dest,"utf8").split(/\\r?\\n/):[];while(out.length&&!out.at(-1))out.pop();',
  '    for(const l of fs.readFileSync(src,"utf8").split(/\\r?\\n/)){const m=/^([A-Za-z_]\\w*)=/.exec(l);if(!m)continue;',
  '      const i=out.findIndex(x=>x.startsWith(m[1]+"="));if(i<0)out.push(l);else out[i]=l;console.log("set "+m[1])}',
  '    fs.writeFileSync(dest,out.join("\\n").replace(/\\n*$/,"\\n"));fs.unlinkSync(src)\' "$1" "$2"',
  '}',
];

export function agentGuide() {
  const maxApps = config.sandbox.maxAppsPerDeveloper;
  const maxTestUsers = config.sandbox.maxTestUsersPerDeveloper;
  const endpoints = endpointGroups().flatMap((g) => g.endpoints);

  return [
    '# CloakTail developer API: guide for coding agents',
    '',
    '> CloakTail is a self-service portal for a Keycloak sandbox realm. With its REST API you register the developer\'s application as an OpenID Connect or SAML client, read its secrets, set up user migration and test logins, then write the code that uses them. Key words MUST, MUST NOT, SHOULD and MAY are as in RFC 2119. Rules are numbered (R1, R2, …) so you can cite them.',
    '',
    `- OpenAPI 3.1 (exact request and response schemas): \`${api}/openapi.json\``,
    `- Reference for people: \`${BASE}/developers/api\``,
    `- User migration protocol (what the application implements): \`${BASE}/migrate/spec.md\``,
    '',
    '## Quick facts',
    '',
    '| Topic | Fact |',
    '|---|---|',
    ...table([
      ['Base URL', `\`${BASE}\`: the scheme, host and port this guide was fetched from (see [Base URL](#base-url))`],
      ['API root', `\`${api}\``],
      ['Authentication', `OAuth 2.0 client credentials at \`POST /api/v1/oauth/token\`, then \`Authorization: Bearer <token>\`. Tokens last ${TOKEN_TTL_S / 60} minutes.`],
      ['Requests', '`Content-Type: application/json`. Field names are snake_case. Unknown fields are rejected with `422 validation_failed`.'],
      ['Responses', 'JSON. Ids are integers. Times are ISO 8601 in UTC (`2026-10-03T07:51:14Z`). URLs are absolute.'],
      ['Secrets as files', '`GET /apps/{id}/env` answers every variable the app needs as `NAME=value` lines; the two secret endpoints take `?format=dotenv`. Write them to a file, never to the terminal.'],
      ['Errors', '`application/problem+json`: `code` (stable), `detail` (how to fix), `field` (when one field is at fault), `errors` (several fields). See [Errors](#errors).'],
      ['Retries', 'GET, PUT, PATCH and DELETE are idempotent. A repeated create answers `409` with the existing resource: see [Retries and changes](#retries-and-changes).'],
      ['Limits', `60 token requests per IP and 1000 calls per credential, per 15 minutes. At most ${maxApps} applications, ${maxTestUsers} test users and ${MAX_CREDENTIALS} credentials per developer.`],
      ['Tools needed', '`curl`, and `node` or `python3`. Not `jq`.'],
      ['Environment', 'Sandbox realm only. Nothing here touches production identities.'],
    ]),
    '',
    '## Base URL',
    '',
    `This guide names no host. Every URL in it starts with \`${BASE}\`, the CloakTail base URL: the scheme, host and port you fetched this guide from. The guide is always at \`${api}/agent.md\`, so if you read it at \`https://cloaktail.example.com/api/v1/agent.md\`, the base URL is \`https://cloaktail.example.com\`.`,
    '',
    'If `CLOAKTAIL_URL` is set in your environment, use it. Otherwise set it yourself, without a trailing slash, so the commands below run as written:',
    '',
    ...sh('export CLOAKTAIL_URL="https://cloaktail.example.com"   # where you fetched this guide from'),
    '',
    'Each CloakTail domain serves its own Keycloak sandbox, and an API credential works only on the domain it was created on: use the base URL the developer gave you. URLs in API responses (`integration.*`, `portal_url`, `test_url`) are already right for that domain: use them as given.',
    '',
    '## What you need',
    '',
    'The developer creates an API credential on CloakTail and gives it to you in your environment, with exactly these names:',
    '',
    '| Variable | Value | Required |',
    '|---|---|---|',
    ...table([
      ['`CLOAKTAIL_CLIENT_ID`', 'The credential\'s client ID, `ctc_…`', 'Yes'],
      ['`CLOAKTAIL_CLIENT_SECRET`', 'The credential\'s secret, `cts_…`', 'Yes'],
      ['`CLOAKTAIL_URL`', 'The base URL', 'No: derive it as above'],
    ]),
    '',
    'They belong in the developer\'s shell profile or in a git-ignored `.env.cloaktail`, never in the application\'s own `.env` (R4). Load and check them without printing them:',
    '',
    ...sh(
      '[ -f .env.cloaktail ] && { set -a; . ./.env.cloaktail; set +a; }',
      'for v in CLOAKTAIL_CLIENT_ID CLOAKTAIL_CLIENT_SECRET; do [ -n "$(printenv $v)" ] && echo "$v set" || echo "$v MISSING"; done',
    ),
    '',
    'If they are stored under other names (e.g. `clientId` and `clientSecret`), map them without printing: `export CLOAKTAIL_CLIENT_ID="$clientId" CLOAKTAIL_CLIENT_SECRET="$clientSecret"`.',
    '',
    `If either is missing, stop and ask the developer to create a credential at \`${BASE}/api-credentials\` and set both variables. Don't ask them to paste the secret into the chat.`,
    '',
    '## Rules',
    '',
    'This API hands you secrets: the CloakTail credential, OIDC client secrets, migration secrets and private keys.',
    '',
    '- **R1.** You MUST NOT print secrets, echo them in the chat, or put them in commit messages, logs, code comments or command-line arguments. Use `ct_token` (below), which passes the credential on stdin. The access token MAY go in a `-H` argument: it expires in 15 minutes.',
    '- **R2.** You MUST write secrets the application needs into its own secret store, a git-ignored `.env` or wherever the project already keeps them, straight from the API to a file (`?format=dotenv`, `GET /apps/{id}/env`) and merged with `env_merge`, so a value is never shown and running a step twice doesn\'t duplicate a variable.',
    '- **R3.** You MUST make sure `.env` (and `.env.cloaktail`, `*.pem` keys) are listed in `.gitignore`, and MUST NOT commit secrets. Commit a `.env.example` with the variable names and empty values.',
    '- **R4.** The application MUST NOT use the CloakTail API credential at runtime, and it MUST NOT be in the application\'s `.env`. At runtime the application needs only its own client secret (OIDC), certificates (SAML) and migration secret.',
    '- **R5.** The application MUST NOT hard-code CloakTail or Keycloak URLs. It reads them from its configuration (the variables in each recipe).',
    '- **R6.** You MUST NOT delete applications, test users or migrated-user links, or rotate secrets, that you didn\'t create in this task without the developer\'s go-ahead.',
    '- **R7.** You SHOULD reuse an access token until a call answers `401`, then get a new one. Don\'t get one per call.',
    '- **R8.** You MUST match what the application already has (variable names, libraries, migration signing method, return URL, keys) before choosing anything new. The values in the recipes are defaults, not instructions.',
    '- **R9.** You SHOULD prefer a well-known, maintained OIDC or SAML library (e.g. openid-client, Auth.js, Spring Security, Authlib, passport-saml/node-saml, python3-saml) over hand-written protocol code.',
    '- **R10.** You MAY show a test user\'s password to the developer: test users exist only in the sandbox.',
    '',
    '## Helpers',
    '',
    'Define these once in your shell. They need `curl` and `node` (`json_get` falls back to `python3`).',
    '',
    ...sh(...HELPERS),
    '',
    '## Getting an access token',
    '',
    ...sh(
      'TOKEN=$(ct_token)',
      '[ -n "$TOKEN" ] && echo "token ok" || echo "no token: check the credential"',
      `curl -s -H "Authorization: Bearer $TOKEN" "${api}/me"`,
    ),
    '',
    `The token endpoint answers \`{"access_token": "…", "token_type": "Bearer", "expires_in": ${TOKEN_TTL_S}, "scope": "…"}\`, or \`401 {"error": "invalid_client"}\` when the credential is wrong, expired or revoked: then stop and ask the developer for a new one.`,
    '',
    '`GET /me` returns whose account you act for, your `scopes`, `quotas` and the sandbox realm\'s OIDC and SAML endpoints. Call it first, and check that `scopes` has what your task needs:',
    '',
    '| Scope | Allows |',
    '|---|---|',
    ...table(Object.entries(SCOPES).map(([s, d]) => [`\`${s}\``, d])),
    '',
    '## Endpoints',
    '',
    `Paths are relative to \`${api}\`. Request and response schemas are in the OpenAPI document.`,
    '',
    '| Method | Path | Scope | Success | Purpose |',
    '|---|---|---|---|---|',
    ...table(endpoints.map((e) => [e.method, `\`${e.path}\``, `\`${e.scope}\``, String(e.ok), e.summary])),
    '',
    `User migration's own endpoints, called by the application's server without a token, are in \`${BASE}/migrate/spec.md\`: \`/migrate/start\`, \`/migrate/check\`, \`/migrate/simulate\` and \`/migrate/status\`.`,
    '',
    '## Decide before you register',
    '',
    'Read the application\'s code and configuration first (R8), and settle these. Ask the developer only what the code can\'t tell you.',
    '',
    '| Decision | Choose |',
    '|---|---|',
    ...table([
      ['Protocol', '`oidc` for new code. `saml` only when the application already uses SAML or its customers require it.'],
      ['`client_type` (OIDC)', '`confidential` when the code that handles the callback runs on a server. `public` for single-page and native apps (no secret, PKCE only).'],
      ['`client_id`', 'What the app\'s config already names. Otherwise lowercase and descriptive, e.g. `<app>-local` for local development. For SAML, the SP entity ID the library uses, often its metadata URL.'],
      ['Callback URL', 'The exact URL of the callback route, with scheme, host, port and path, e.g. `http://localhost:4000/auth/callback`. Find the port in the app\'s config or start script.'],
      ['Deployed URLs', 'Only add them if the developer gives them. Never guess a production URL.'],
    ]),
    '',
    '## Recipe: add OpenID Connect login',
    '',
    '1. `GET /apps`. If an application with your `client_id` is listed, use its `id` (and `PATCH` its `redirect_uris` if needed) instead of registering another.',
    '2. Register it:',
    '',
    ...sh(
      `curl -s -X POST "${api}/apps" -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' -d '{`,
      '  "protocol": "oidc",',
      '  "name": "Billing (local)",',
      '  "client_id": "billing-local",',
      '  "client_type": "confidential",',
      '  "redirect_uris": ["http://localhost:4000/auth/callback"],',
      '  "post_logout_redirect_uris": ["http://localhost:4000/"]',
      '}\'',
    ),
    '',
    '   The answer is `201` with the application, including its `id` and `integration`. `require_pkce` defaults to `true`, so the application MUST send a PKCE S256 code challenge. On `409 duplicate_client_id` with `existing_app_id`, the app is already yours: continue with that id. Without `existing_app_id`, another developer has that client ID: choose another.',
    '3. Write its configuration into the application\'s `.env` (R2). `GET /apps/{id}/env` answers these lines:',
    '',
    '| Variable | Value |',
    '|---|---|',
    ...table([
      ['`OIDC_ISSUER`', '`integration.issuer`. The library discovers the endpoints from it; don\'t hard-code them.'],
      ['`OIDC_CLIENT_ID`', '`client_id`'],
      ['`OIDC_CLIENT_SECRET`', 'Confidential clients only'],
      ['`OIDC_REDIRECT_URI`', 'The first registered redirect URI'],
      ['`OIDC_POST_LOGOUT_REDIRECT_URI`', 'The first post-logout redirect URI, when there is one'],
    ]),
    '',
    ...sh(
      `curl -s --fail-with-body -H "Authorization: Bearer $TOKEN" "${api}/apps/$APP_ID/env" -o .env.cloaktail-app \\`,
      '  && env_merge .env.cloaktail-app .env',
    ),
    '',
    '   If the application already uses other names (R8), rename the lines in `.env` after merging, or read them under its names in code.',
    '4. Write the login: authorization code flow with PKCE (S256), `scope=openid profile email`, check `state` and `nonce`, validate the ID token (the library does this), keep the session server-side. Logout redirects to the end-session endpoint with `id_token_hint` and a registered `post_logout_redirect_uri`.',
    '5. Test it: [Testing a login](#testing-a-login).',
    '',
    ...done([
      '`GET /apps/{id}` shows the app, with your callback URL in `redirect_uris`.',
      '`.env` has each variable once (no `OIDC_CLIENT_SECRET` for a public client), `.env` is git-ignored, and `.env.example` lists the names.',
      'The code reads every value from configuration, uses PKCE S256, and checks `state` and `nonce`.',
      '`GET /apps/{id}/tests` has a run with `ok: true` from after your changes.',
      'You told the developer what you changed, how to run it, and which test user to sign in with.',
    ]),
    '',
    '## Recipe: add SAML single sign-on',
    '',
    '1. If the application has SP metadata XML, `POST /saml-metadata` with `{"metadata": "<EntityDescriptor …>"}` turns it into fields: add a `name` and send them to `POST /apps`. Otherwise register directly:',
    '',
    '```json',
    JSON.stringify({ protocol: 'saml', name: 'Billing (local)', client_id: 'http://localhost:4000/saml/metadata', acs_url: 'http://localhost:4000/saml/acs', name_id_format: 'email', attributes: ['email', 'firstName', 'lastName'] }, null, 2),
    '```',
    '',
    '2. Write its configuration with `GET /apps/{id}/env` and `env_merge`, as in the OIDC recipe. The lines are:',
    '',
    '| Variable | Value |',
    '|---|---|',
    ...table([
      ['`SAML_IDP_METADATA_URL`', 'The IdP metadata URL. Preferred: the library reads the SSO URL and certificate from it.'],
      ['`SAML_IDP_SSO_URL`', 'For libraries that can\'t read metadata'],
      ['`SAML_IDP_CERT`', 'The IdP signing certificate, base64 DER on one line (add the PEM header and footer if the library wants PEM)'],
      ['`SAML_SP_ENTITY_ID`', '`client_id`'],
      ['`SAML_ACS_URL`', '`acs_url`'],
    ]),
    '',
    '   The application MUST verify the response or assertion signature with the IdP certificate.',
    '3. If the application signs its AuthnRequests (`client_signature: true`) or wants encrypted assertions (`encrypt_assertions: true`), it needs a key pair. Use the one it already has (R8); otherwise `POST /tools/certificate` with `{"common_name": "<app host>"}`, write `private_key_pem` straight to a git-ignored file with node (R1, R2), and `PATCH` the app with `certificate_pem` as `signing_cert` or `encryption_cert`.',
    '4. Test it: [Testing a login](#testing-a-login). A client with `client_signature: true` can\'t be tested from CloakTail (`400 signed_requests_required`), because only the application holds its key: test through the application instead.',
    '',
    ...done([
      '`GET /apps/{id}` shows the app with the application\'s real ACS URL.',
      'The configuration has the variables above once each, and any private key is in a git-ignored file.',
      'The code verifies signatures with the IdP certificate and reads the attributes the app needs.',
      '`GET /apps/{id}/tests` has a run with `ok: true` from after your changes (unless `client_signature` is on).',
      'You told the developer what you changed and how to test it.',
    ]),
    '',
    '## Recipe: set up user migration',
    '',
    'For an application that signs its users in itself today and is moving to Keycloak. It keeps checking old passwords until each user has moved: the first time a user signs in, the application sends them to CloakTail, where they choose a new password and add an authenticator app; CloakTail creates their Keycloak account and sends them back, and the application lets them in without a second sign-in. From their next sign-in they use Keycloak. Register the application first (recipes above): its `client_id` is the `iss` of migration requests.',
    '',
    '1. **Read what is already there (R8).** `GET /apps/{id}/migration`, and search the application for an existing migration setup: a return URL route, a signing key or JWKS endpoint, `CLOAKTAIL_*` variables. Keep its signing method, return URL and keys. Choose new values only for what is missing.',
    '2. **Set up migration** with the signing method the application uses. A first setup answers `201`; later changes answer `200`, and fields you leave out keep their value. One example per method:',
    '',
    '| `request_signing` | Use when | Also send |',
    '|---|---|---|',
    ...table([
      ['`secret`', 'The application has no signing key of its own. Requests are HS256 with the migration secret.', 'Nothing'],
      ['`public_key`', 'The application has a private key and no JWKS endpoint.', '`public_key`: its PEM public key'],
      ['`jwks`', 'The application already publishes a JWKS. Requests carry a `kid` from it.', '`jwks_url`: reachable from CloakTail'],
    ]),
    '',
    ...sh(
      '# secret',
      `curl -s -X PUT "${api}/apps/$APP_ID/migration" -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \\`,
      '  -d \'{"return_urls": ["http://localhost:4000/migrated"], "request_signing": "secret"}\'',
      '',
      '# public_key (the PEM read from the app\'s public key file by node, so newlines are escaped correctly)',
      'node -e \'const fs=require("fs");process.stdout.write(JSON.stringify({return_urls:["http://localhost:4000/migrated"],request_signing:"public_key",public_key:fs.readFileSync("keys/migration-public.pem","utf8")}))\' |',
      `  curl -s -X PUT "${api}/apps/$APP_ID/migration" -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' -d @-`,
      '',
      '# jwks',
      `curl -s -X PUT "${api}/apps/$APP_ID/migration" -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \\`,
      '  -d \'{"return_urls": ["http://localhost:4000/migrated"], "request_signing": "jwks", "jwks_url": "https://myapp.example.com/.well-known/jwks.json"}\'',
    ),
    '',
    '   **`require_otp`** defaults to `true`: migrated users add an authenticator app on the CloakTail migration page, next to their new password. Keep `true` unless the developer says otherwise; it is what production should use. Send `"require_otp": false` only when the developer wants quicker sandbox tests, and tell them it is off.',
    '',
    '   The answer\'s `warnings` are objects with a `code`, `who_can_fix`, `impact` and `ignorable_if`. Act on `jwks_unreachable` and `jwks_no_usable_key` (impact High: every request would be refused). Tell the developer about `who_can_fix: "admin"` warnings; they don\'t stop migration.',
    '3. **Write its configuration** with `GET /apps/{id}/env` and `env_merge`, as in the OIDC recipe. With migration set up, it adds:',
    '',
    '| Variable | Value |',
    '|---|---|',
    ...table([
      ['`CLOAKTAIL_URL`', 'The base URL. Requests go to `$CLOAKTAIL_URL/migrate/start`; their `aud` is `$CLOAKTAIL_URL/migrate`.'],
      ['`CLOAKTAIL_MIGRATION_SECRET`', 'Signs requests (with `secret`) and verifies results (always)'],
      ['`OIDC_CLIENT_ID` or `SAML_SP_ENTITY_ID`', 'The `iss` of requests and the `aud` of results'],
    ]),
    '',
    `4. **Implement the protocol** in \`${BASE}/migrate/spec.md\` exactly: the per-user migrated flag, the signed request after the old password checks out, the return URL handler that verifies the result and starts the session after \`created\`, Keycloak sign-in for migrated users, and recovery of lost results with \`POST /migrate/status\`.`,
    `5. **Check a request** your code builds with \`POST ${BASE}/migrate/check\` and \`{"request": "<JWT>"}\` (no token: the request's signature authenticates it). It reports exactly what \`/migrate/start\` would refuse.`,
    `6. **Test the return URL handler** with \`POST ${BASE}/migrate/simulate\` and \`{"request": "<JWT>", "status": "<status>"}\` for every status in the spec. It answers a signed result marked \`simulated: true\` and creates no one.`,
    '',
    'CloakTail keeps its own record of which Keycloak user each `sub` became (`GET /apps/{id}/migration/users`), so a returning user is always answered `already_migrated`. A user whose username or email was already taken gets `conflict`: when the developer confirms the existing Keycloak account is theirs, link it with `PUT /apps/{id}/migration/users/{sub}` and `{"username": "<keycloak username or email>"}`, and the next request answers `already_migrated`.',
    '',
    ...done([
      '`GET /apps/{id}/migration` shows `configured: true`, `enabled: true`, the application\'s signing method and return URL, and no High-impact `warnings`.',
      '`.env` has `CLOAKTAIL_URL` and `CLOAKTAIL_MIGRATION_SECRET` once each, and it is git-ignored.',
      '`POST /migrate/check` answers `ok: true` for a request built by the application\'s own code.',
      'The return URL handler handles every status from `/migrate/simulate` as the spec says (`created` signs the user in without Keycloak; `already_migrated` starts the Keycloak sign-in), and rejects a result with a wrong signature, `aud` or `state`.',
      'The application calls `POST /migrate/status` when a user it sent never came back, and records them when `migrated` is true.',
      '`GET /apps/{id}/migration/events` shows no `rejected` requests from your tests, or you know why.',
      'You told the developer about any `warnings` and whether `require_otp` is on.',
    ]),
    '',
    '## Testing a login',
    '',
    'A real login needs a person at a browser. Prepare it, then hand over:',
    '',
    `1. \`GET /test-users\`. If there is none, \`POST /test-users\` with \`username\`, \`email\`, \`first_name\`, \`last_name\` and a generated \`password\` of at least 8 characters (at most ${maxTestUsers} test users per developer).`,
    '2. `POST /apps/{id}/tests` answers `201` with a `test_url`, valid for 10 minutes. CloakTail plays the application for one login, so this tests the Keycloak client settings, not the application\'s code.',
    '3. Give the developer the `test_url`, the test user\'s username and password (R10), and ask them to open it within 10 minutes.',
    '4. Poll `GET /apps/{id}/tests` every 5 seconds, for at most 10 minutes, until a run newer than step 2 appears. Read it with `GET /apps/{id}/tests/{runId}`: `ok`, the checks, and the assertion or tokens and their claims. If `ok` is false, fix what the failing checks name and test again.',
    '5. To test the application\'s own code, ask the developer to start it and sign in as the test user.',
    '',
    '## Retries and changes',
    '',
    '- A repeated `POST /apps` with the same `client_id` answers `409 duplicate_client_id` with `existing_app_id` when the app is yours: continue with it. A repeated test user answers `409 duplicate_username`.',
    '- `PATCH /apps/{id}` changes only the fields you send. Arrays (`redirect_uris`, `attributes`, …) replace the whole list: send the complete list. `client_id` and `protocol` can\'t change.',
    '- `PUT /apps/{id}/migration` keeps fields you leave out. `PUT /apps/{id}/migration/users/{sub}` replaces that user\'s link.',
    '- `env_merge` replaces variables that already exist, so writing configuration twice is safe.',
    '- Rotating a secret stops the old one at once. Rotate only when the developer asks (R6), then write the new value with `env_merge` straight away.',
    '',
    '## Errors',
    '',
    'Errors are `application/problem+json` with a stable `code`, a `detail` that says how to fix it, and `field` when one request field is at fault. The token endpoint answers OAuth errors instead (`error`, `error_description`). Act on `code`, not on the wording of `detail`.',
    '',
    '| HTTP | `code` | What to do |',
    '|---|---|---|',
    ...table([
      ['401', '`invalid_token`', 'Get a new access token (R7). If the token endpoint then answers `invalid_client`, stop: the credential expired or was revoked. Ask the developer for a new one.'],
      ['403', '`insufficient_scope`', 'Stop: the credential lacks the scope named in `detail`. Ask the developer for a credential with it.'],
      ['403', '`forbidden`', 'Stop: the developer\'s account lacks the developer role. An administrator must grant it.'],
      ['404', '`not_found`', 'Wrong id, or the app belongs to someone else. List with `GET /apps`.'],
      ['404', '`keycloak_client_missing`', 'The Keycloak client was deleted outside CloakTail. Ask the developer, then delete the app and register it again.'],
      ['404', '`migration_not_configured`', '`PUT /apps/{id}/migration` first.'],
      ['404', '`keycloak_user_not_found`', 'No user with that username in the sandbox realm: check it with the developer.'],
      ['409', '`duplicate_client_id`', 'Continue with `existing_app_id` if present; otherwise choose another `client_id`.'],
      ['409', '`duplicate_username`', 'Check `GET /test-users`: use yours if it is there, otherwise choose another username.'],
      ['409', '`secret_unreadable`', 'Ask the developer, then rotate the migration secret.'],
      ['400', '`public_client`', 'Public clients have no secret: use PKCE only.'],
      ['400', '`not_oidc`', 'Only OIDC apps have a client secret.'],
      ['400', '`signed_requests_required`', 'Test through the application: see the SAML recipe, step 4.'],
      ['400', '`invalid_json`', 'Send valid JSON with `Content-Type: application/json`.'],
      ['413', '`too_large`', 'The body is over 1 MB.'],
      ['422', '`validation_failed`', 'Fix `field` as `detail` says; `errors` lists every field when there are several. Then send again.'],
      ['422', '`quota_exceeded`', 'Stop and ask the developer which existing resource to delete (R6).'],
      ['422', '`keycloak_rejected`', 'Keycloak refused the values; `detail` is its message. Fix them and send again.'],
      ['429', '`rate_limited`', 'Wait 15 minutes, or tell the developer. Reuse tokens (R7).'],
      ['502', '`keycloak_error`', 'Keycloak is unreachable. Retry once after 30 seconds, then tell the developer.'],
    ]),
    '',
  ].join('\n');
}
