-- CloakTail schema (PostgreSQL). The app creates anything missing here on startup, as dbuser or,
-- when set, as dbadminuser (which then grants dbuser access). To create it by hand instead:
--   psql -d <database> -f db/schema.sql
--   GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO <app user>;
-- Timestamps are UTC text 'YYYY-MM-DD HH:MM:SS', as the app compares and displays them as strings.

-- Named Keycloak connections. Each serves the domains listed for it in profile_domains, and owns its
-- own users, roles and sandbox data (the profile_id columns below). See keycloakProfiles.js.
CREATE TABLE IF NOT EXISTS keycloak_profiles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  settings    TEXT NOT NULL,            -- JSON, everything except client secrets
  secrets     TEXT NOT NULL DEFAULT '', -- encrypted JSON of the client secrets
  created_by  TEXT,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_by  TEXT,
  updated_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
-- Profile names are unique regardless of case.
CREATE UNIQUE INDEX IF NOT EXISTS keycloak_profiles_name_ci ON keycloak_profiles (lower(name));
-- Which profile serves each domain. origin is lowercase scheme://host[:port], e.g. https://a.example.com.
CREATE TABLE IF NOT EXISTS profile_domains (
  origin     TEXT PRIMARY KEY,
  profile_id INTEGER NOT NULL REFERENCES keycloak_profiles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  profile_id    INTEGER NOT NULL REFERENCES keycloak_profiles(id) ON DELETE CASCADE,
  username      TEXT NOT NULL,
  keycloak_id   TEXT,
  email         TEXT,
  first_name    TEXT,
  last_name     TEXT,
  created_at    TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  last_login_at TEXT,
  PRIMARY KEY (profile_id, username)
);
CREATE TABLE IF NOT EXISTS roles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id  INTEGER NOT NULL REFERENCES keycloak_profiles(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  is_system   INTEGER NOT NULL DEFAULT 0,
  UNIQUE (profile_id, name)
);
CREATE TABLE IF NOT EXISTS permissions (
  key         TEXT PRIMARY KEY,
  description TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id        INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_key TEXT NOT NULL REFERENCES permissions(key) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_key)
);
CREATE TABLE IF NOT EXISTS user_roles (
  profile_id INTEGER NOT NULL,
  username   TEXT NOT NULL,
  role_id    INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (profile_id, username, role_id),
  FOREIGN KEY (profile_id, username) REFERENCES users(profile_id, username) ON DELETE CASCADE
);

-- Developer-owned SAML and OIDC clients in the profile's sandbox realm (Keycloak holds their configuration).
CREATE TABLE IF NOT EXISTS apps (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id INTEGER NOT NULL REFERENCES keycloak_profiles(id) ON DELETE CASCADE,
  protocol   TEXT NOT NULL DEFAULT 'saml' CHECK (protocol IN ('saml', 'oidc')),
  owner      TEXT NOT NULL,
  kc_id      TEXT NOT NULL,
  client_id  TEXT NOT NULL,
  name       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (profile_id, kc_id),
  UNIQUE (profile_id, client_id)
);
CREATE TABLE IF NOT EXISTS test_users (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id INTEGER NOT NULL REFERENCES keycloak_profiles(id) ON DELETE CASCADE,
  owner      TEXT NOT NULL,
  kc_id      TEXT NOT NULL,
  username   TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (profile_id, kc_id),
  UNIQUE (profile_id, username)
);
CREATE TABLE IF NOT EXISTS test_runs (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_id     INTEGER NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
  ok         INTEGER NOT NULL,
  summary    TEXT NOT NULL,
  result     TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

-- Applications that send their users to /migrate to move them into Keycloak (see migrationClients.js).
-- Users are created in the profile's sandbox realm, with the sandbox service account.
CREATE TABLE IF NOT EXISTS migration_clients (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id  INTEGER NOT NULL REFERENCES keycloak_profiles(id) ON DELETE CASCADE,
  client_id   TEXT NOT NULL,             -- the "iss" of the application's requests
  name        TEXT NOT NULL,
  enabled     INTEGER NOT NULL DEFAULT 1,
  settings    TEXT NOT NULL,             -- JSON, everything except secrets
  secrets     TEXT NOT NULL DEFAULT '',  -- encrypted JSON: the client secret
  created_by  TEXT,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_by  TEXT,
  updated_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (profile_id, client_id)
);
-- One row per migration request: the audit trail, and replay protection (each request id once).
CREATE TABLE IF NOT EXISTS migration_events (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_pk   INTEGER NOT NULL REFERENCES migration_clients(id) ON DELETE CASCADE,
  jti         TEXT NOT NULL,
  legacy_id   TEXT NOT NULL,
  username    TEXT NOT NULL,
  status      TEXT NOT NULL,             -- started, created, already_migrated, conflict, cancelled, expired, error
  keycloak_id TEXT,
  detail      TEXT,
  ip          TEXT,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (client_pk, jti)
);
CREATE INDEX IF NOT EXISTS migration_events_client_created ON migration_events (client_pk, id DESC);

-- Small app-wide values set from the admin console.
CREATE TABLE IF NOT EXISTS settings (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_by TEXT,
  updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
-- The portal's SAML signing key pairs, one set per Keycloak profile: at most one active and one
-- pending (a replacement waiting to be imported into that profile's Keycloak). See spKeys.js.
CREATE TABLE IF NOT EXISTS sp_keys (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id  INTEGER NOT NULL REFERENCES keycloak_profiles(id) ON DELETE CASCADE,
  status      TEXT NOT NULL CHECK (status IN ('active', 'pending')),
  certificate TEXT NOT NULL,            -- PEM, public
  private_key TEXT NOT NULL,            -- PEM, encrypted
  created_by  TEXT,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  activated_at TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS sp_keys_one_per_profile_status ON sp_keys (profile_id, status);
-- Admin console accounts. Local on purpose: they must work even when Keycloak is misconfigured.
CREATE TABLE IF NOT EXISTS admin_accounts (
  username             TEXT PRIMARY KEY,
  password_hash        TEXT NOT NULL,
  must_change_password INTEGER NOT NULL DEFAULT 1,
  password_changed_at  TEXT NOT NULL,
  failed_attempts      INTEGER NOT NULL DEFAULT 0,
  locked_until         TEXT,
  created_by           TEXT,
  created_at           TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  last_login_at        TEXT
);
-- Browser sessions (the express-session store, see session.js). Shared, so they survive restarts
-- and work across several app instances.
CREATE TABLE IF NOT EXISTS sessions (
  sid        TEXT PRIMARY KEY,
  sess       TEXT NOT NULL,             -- JSON
  expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_expires_at ON sessions (expires_at);
