-- CloakTail schema (PostgreSQL). The app creates anything missing here on startup, as dbuser or,
-- when set, as dbadminuser (which then grants dbuser access). To create it by hand instead:
--   psql -d <database> -f db/schema.sql
--   GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO <app user>;
-- Timestamps are UTC text 'YYYY-MM-DD HH:MM:SS', as the app compares and displays them as strings.

CREATE TABLE IF NOT EXISTS users (
  username      TEXT PRIMARY KEY,
  keycloak_id   TEXT,
  email         TEXT,
  first_name    TEXT,
  last_name     TEXT,
  created_at    TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  last_login_at TEXT
);
CREATE TABLE IF NOT EXISTS roles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  is_system   INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS permissions (
  key         TEXT PRIMARY KEY,
  description TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id        INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_key TEXT NOT NULL REFERENCES permissions(key) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_key)
);
CREATE TABLE IF NOT EXISTS user_roles (
  username TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
  role_id  INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (username, role_id)
);

-- Developer-owned SAML clients in the sandbox realm (Keycloak holds their configuration).
CREATE TABLE IF NOT EXISTS apps (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner      TEXT NOT NULL,
  kc_id      TEXT NOT NULL UNIQUE,
  client_id  TEXT NOT NULL UNIQUE,
  name       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS test_users (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner      TEXT NOT NULL,
  kc_id      TEXT NOT NULL UNIQUE,
  username   TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS test_runs (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_id     INTEGER NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
  ok         INTEGER NOT NULL,
  summary    TEXT NOT NULL,
  result     TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

-- Small app-wide values set from the admin console, e.g. which Keycloak profile is active.
CREATE TABLE IF NOT EXISTS settings (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_by TEXT,
  updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
-- The portal's SAML signing key pair. At most one active and one pending (a replacement waiting
-- to be imported into Keycloak). See spKeys.js.
CREATE TABLE IF NOT EXISTS sp_keys (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status      TEXT NOT NULL CHECK (status IN ('active', 'pending')),
  certificate TEXT NOT NULL,            -- PEM, public
  private_key TEXT NOT NULL,            -- PEM, encrypted
  created_by  TEXT,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  activated_at TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS sp_keys_one_per_status ON sp_keys (status);
-- Named Keycloak connections; one is active (settings.active_keycloak_profile). See keycloakProfiles.js.
CREATE TABLE IF NOT EXISTS keycloak_profiles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  settings    TEXT NOT NULL,            -- JSON, everything except client secrets
  secrets     TEXT NOT NULL DEFAULT '', -- encrypted JSON of the client secrets
  created_by  TEXT,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_by  TEXT,
  updated_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
-- Profile names are unique regardless of case.
CREATE UNIQUE INDEX IF NOT EXISTS keycloak_profiles_name_ci ON keycloak_profiles (lower(name));
-- Admin console accounts. Local on purpose: they must work even when Keycloak is misconfigured.
CREATE TABLE IF NOT EXISTS admin_accounts (
  username             TEXT PRIMARY KEY,
  password_hash        TEXT NOT NULL,
  must_change_password INTEGER NOT NULL DEFAULT 1,
  password_changed_at  TEXT NOT NULL,
  failed_attempts      INTEGER NOT NULL DEFAULT 0,
  locked_until         TEXT,
  created_by           TEXT,
  created_at           TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  last_login_at        TEXT
);
-- Browser sessions (the express-session store, see session.js). Shared, so they survive restarts
-- and work across several app instances.
CREATE TABLE IF NOT EXISTS sessions (
  sid        TEXT PRIMARY KEY,
  sess       TEXT NOT NULL,             -- JSON
  expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_expires_at ON sessions (expires_at);
